SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO 
WHERE ITEM_ID NOT IN
(
    SELECT DISTINCT(i.ITEM_ID)
    FROM ITEM_TREE AS i
    JOIN ITEM_TREE AS ii
    ON i.ITEM_ID = ii.PARENT_ITEM_ID
)
ORDER BY ITEM_ID DESC