SELECT ED.ID, CASE
    WHEN PD.CHILD_COUNT IS NULL
    THEN 0
    ELSE PD.CHILD_COUNT
    END AS CHILD_COUNT
FROM ECOLI_DATA AS ED
LEFT JOIN
(
    SELECT PARENT_ID, COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
) AS PD
ON ED.ID = PD.PARENT_ID