SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME
FROM ANIMAL_INS AS AI
JOIN 
(
    SELECT *
    FROM ANIMAL_OUTS
    WHERE SEX_UPON_OUTCOME LIKE 'Spayed%' OR SEX_UPON_OUTCOME LIKE 'Neutered%'
) AS O
ON AI.ANIMAL_ID = O.ANIMAL_ID
WHERE AI.SEX_UPON_INTAKE LIKE 'Intact%';