SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, FP.PRODUCT_CD, FP.CATEGORY, FP.PRICE
FROM 
FOOD_PRODUCT AS FP
JOIN
(
    SELECT MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
) AS MAX_INFO
ON FP.PRICE = MAX_INFO.MAX_PRICE
