SELECT MP.MEMBER_NAME, M.REVIEW_TEXT, DATE_FORMAT(M.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE AS MP
JOIN
(
    (
        SELECT MEMBER_ID, REVIEW_TEXT, REVIEW_DATE
        FROM REST_REVIEW
    ) AS M
    JOIN
    (
        SELECT MEMBER_ID, COUNT(*) AS MAX_COUNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    ) AS MM
    ON M.MEMBER_ID = MM.MEMBER_ID
    JOIN
    (
        SELECT COUNT(*) AS MAX_COUNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(*) DESC
        LIMIT 1
    ) AS MMM
    ON MM.MAX_COUNT = MMM.MAX_COUNT
)
ON MP.MEMBER_ID = M.MEMBER_ID
ORDER BY REVIEW_DATE ASC, M.REVIEW_TEXT ASC