SELECT MONTH(START_DATE) AS MONTH, CC.CAR_ID, COUNT(*) AS RECORDS
FROM
(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
) AS TC
JOIN
CAR_RENTAL_COMPANY_RENTAL_HISTORY CC
ON CC.CAR_ID = TC.CAR_ID
WHERE CC.START_DATE BETWEEN '2022-08-01' AND '2022-10-31' 
GROUP BY MONTH(START_DATE), CC.CAR_ID
ORDER BY MONTH ASC, CC.CAR_ID DESC