-- 상반기 아이스크림 총주문량이 3,000보다 높으면서 아이스크림의 주 성분이 과일인 아이스크림의 맛을 총주문량이 큰 순서대로 조회하는 SQL 문을 작성해주세요.
-- ICECREAM_INFO
-- FIRST_HALF

SELECT f.FLAVOR
FROM FIRST_HALF f
JOIN ICECREAM_INFO i
  ON f.FLAVOR = i.FLAVOR
WHERE f.TOTAL_ORDER > 3000
  AND i.INGREDIENT_TYPE = 'fruit_based'
ORDER BY f.TOTAL_ORDER DESC;

# SELECT *
# FROM FIRST_HALF FH
# JOIN ICECREAM_INFO II ON FH.FLAVOR = II.FLAVOR
# WHERE FH.TOTAL_ORDER > 3000
#   AND II.INGREDIENT_TYPE = 'fruit_based'
# ORDER BY FH.TOTAL_ORDER DESC;